mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: uuid
  configuration:
    cache-enabled: false
    call-setters-on-nulls: true
spring:
  mvc:
    locale: zh_CN